Repository fykosak/fksdb, pull requests merged in 2018-02, with the labels that each got.

#243 [tasks] use Form from correct namespace
  app/OrgModule/presenters/TasksPresenter.php
Labels: bug

#244 [FOF-HORI] Informácie o naplnení B a C
  data/events/fyziklani.form.latte
Labels: FOF

#247 hotfix grigu
  app/Components/Grids/Fyziklani/FyziklaniSubmitsGrid.php
Labels: FOF, bug

#245 Stránka po zadaní cez QR-kód
  app/FyziklaniModule/presenters/SubmitPresenter.php
  app/FyziklaniModule/templates/Submit/autoClose.latte
Labels: FOF
