Repository fykosak/fksdb, pull requests merged in 2018-10, with the labels that each got.

#362 Testy ubytovania DSEF 24
  app/Components/Forms/Controls/PersonAccommodation/Handler.php
  app/Components/Forms/Controls/PersonAccommodation/Matrix.php
  app/Components/Forms/Controls/ReferencedId.php
  app/Components/React/IReactComponent.php
  app/model/Persons/ReferencedPersonHandler.php
  data/events/dsef/dsef24.neon
  tests/Events/Accommodation/Accommodation.create.phpt
  tests/Events/Accommodation/Accommodation.delete.phpt
  tests/Events/Accommodation/Accommodation.limit.phpt
  tests/Events/Accommodation/AccommodationTestCase.php
  tests/clear-database.sh
Labels: code quality, events

#363 Dev fol category (URGENT)
  app/model/Events/Spec/Fol/CategoryProcessing.php
  data/events/fol/fol1.neon
  data/events/fol/fol8.neon
  i18n/locale/en/LC_MESSAGES/messages.po
Labels: bug

#370 Remove PHP5.6 tests
  .travis.yml
Labels: PHP 5.6 incompatible

#369 update ORM to PHP7.0
  app/model/Exports/StoredQuery.php
  app/model/ORM/abstract/AbstractModelSingle.php
  app/model/ORM/models/ModelAuthToken.php
  app/model/ORM/models/ModelContest.php
  app/model/ORM/models/ModelContestant.php
  app/model/ORM/models/ModelEvent.php
  app/model/ORM/models/ModelEventAccommodation.php
  app/model/ORM/models/ModelEventOrg.php
  app/model/ORM/models/ModelEventParticipant.php
  app/model/ORM/models/ModelEventPersonAccommodation.php
  app/model/ORM/models/ModelLogin.php
  app/model/ORM/models/ModelOrg.php
  app/model/ORM/models/ModelPerson.php
  app/model/ORM/models/ModelPersonHistory.php
  app/model/ORM/models/ModelPersonInfo.php
  app/model/ORM/models/ModelPostContact.php
  app/model/ORM/models/ModelSchool.php
  app/model/ORM/models/ModelStoredQuery.php
  app/model/ORM/models/ModelSubmit.php
  app/model/ORM/models/ModelTask.php
  app/model/ORM/models/ModelTaskContribution.php
  app/model/ORM/models/ModelTaskStudyYear.php
  app/model/ORM/models/ModelTeacher.php
  tests/Events/Accommodation/Accommodation.delete.phpt
Labels: PHP 5.6 incompatible, code quality

#373 add register to dispatch screen
  app/presenters/DispatchPresenter.php
  app/templates/Dispatch/default.latte
Labels: UI & Front-end (CSS+JS+HTML)

#376 [export] hotfix ORDER BY in inner query
  app/model/Exports/StoredQuery.php
Labels: bug

#378 ORDER BY statement in a FROM Subquery is Ignored
  app/model/Exports/StoredQuery.php
Labels: bug, database

#368 Dev accommodation component2
  app/Components/Forms/Controls/PersonAccommodation/AccommodationField.php
  app/Components/Forms/Controls/PersonAccommodation/Factory.php
  app/Components/Forms/Controls/PersonAccommodation/Handler.php
  app/Components/Forms/Controls/PersonAccommodation/MatrixField.php
  app/Components/Forms/Controls/PersonAccommodation/MultiHotelsField.php
  app/Components/Forms/Controls/PersonAccommodation/MultiNightsField.php
  app/Components/Forms/Controls/PersonAccommodation/SingleField.php
  app/Components/Forms/Factories/EventAccommodation/Factory.php
  app/Components/Forms/Factories/EventFactory.php
  app/Components/Forms/Factories/FlagFactory.php
  app/Components/Forms/Factories/FyziklaniFactory.php
  app/Components/Forms/Factories/LoginFactory.php
  app/Components/Forms/Factories/OrgFactory.php
  app/Components/Forms/Factories/PersonAccommodationFactory.php
  app/Components/Forms/Factories/PersonFactory.php
  app/Components/Forms/Factories/PersonHistoryFactory.php
  app/Components/Forms/Factories/PersonInfoFactory.php
  app/Components/Forms/Factories/ReferencedPerson/ReferencedEventPersonFactory.php
  app/Components/Forms/Factories/SchoolFactory.php
  app/Components/React/Fyziklani/FyziklaniModule.php
  app/Components/React/Fyziklani/Results.php
  app/Components/React/Fyziklani/RoutingEdit.php
  app/Components/React/IReactComponent.php
  app/model/Persons/ReferencedPersonHandler.php
  app/templates/@layout.v4.latte
  data/events/dsef/dsef24.neon
  i18n/locale/cs/LC_MESSAGES/messages.po
  i18n/locale/en/LC_MESSAGES/messages.po
  i18n/locale/sk/LC_MESSAGES/messages.po
  tests/Events/Accommodation/AccommodationTestCase.php
  www/js/TypeScriptSources/src/events/accommodation/components/capacity-label.tsx
  www/js/TypeScriptSources/src/events/accommodation/components/index.tsx
  www/js/TypeScriptSources/src/events/accommodation/components/input-connector.tsx
  www/js/TypeScriptSources/src/events/accommodation/components/matrix/index.tsx
  www/js/TypeScriptSources/src/events/accommodation/components/matrix/row.tsx
  www/js/TypeScriptSources/src/events/accommodation/components/rows/single-row.tsx
  www/js/TypeScriptSources/src/events/accommodation/components/single/index.tsx
  www/js/TypeScriptSources/src/events/accommodation/index.tsx
  www/js/TypeScriptSources/src/events/accommodation/middleware/dates.ts
  www/js/TypeScriptSources/src/i18n/i18n-data.ts
  www/js/TypeScriptSources/src/i18n/i18n.ts
  www/js/TypeScriptSources/webpack.config.js
  www/js/bundle-all.min.js
Labels: FOF, PHP 5.6 incompatible, code quality, events

#382 Pridanie poličiek pre DPP
  app/Components/Forms/Factories/Person/BornFamilyNameField.php
  app/Components/Forms/Factories/PersonFactory.php
  app/Components/Forms/Factories/PersonInfo/AcademicDegreePrefixField.php
  app/Components/Forms/Factories/PersonInfo/AcademicDegreeSuffixField.php
  app/Components/Forms/Factories/PersonInfo/CitizenshipField.php
  app/Components/Forms/Factories/PersonInfo/EmployerField.php
  app/Components/Forms/Factories/PersonInfo/HealthInsuranceField.php
  app/Components/Forms/Factories/PersonInfoFactory.php
  app/config/contests.neon
  app/model/ORM/models/ModelRegion.php
  sql/schema.sql
Labels: database

#390 Update points presenter to v4
  app/OrgModule/presenters/PointsPresenter.php
  app/OrgModule/templates/Points/default.latte
  app/PublicModule/presenters/EventPaymentPresenter.php
  app/PublicModule/templates/EventPayment/new.latte
  www/css/points.css
Labels: UI & Front-end (CSS+JS+HTML)

#392 Kompilacia SCSS
  app/templates/@layout.v4.latte
  www/css/bundle.css
  www/css/scss/fyziklani-results.scss
  www/css/scss/index.scss
  www/css/style.v4.css
Labels: UI & Front-end (CSS+JS+HTML), enhancement
