Repository fykosak/fksdb, pull requests merged in 2018-07, with the labels that each got.

#290 [series] new computation of current series
  app/model/SeriesCalculator.php
Labels: enhancement

#135 BrawlChooser
  app/Components/Controls/Choosers/BrawlChooser.latte
  app/Components/Controls/Choosers/BrawlChooser.php
  app/FyziklaniModule/presenters/BasePresenter.php
  app/FyziklaniModule/templates/@layout.latte
  app/FyziklaniModule/templates/Close/table.latte
  app/FyziklaniModule/templates/Close/team.latte
  app/FyziklaniModule/templates/Dashboard/default.latte
  app/FyziklaniModule/templates/Results/default.latte
  app/FyziklaniModule/templates/Rooms/default.latte
  app/FyziklaniModule/templates/Rooms/download.latte
  app/FyziklaniModule/templates/Rooms/edit.latte
  app/FyziklaniModule/templates/Submit/autoClose.latte
  app/FyziklaniModule/templates/Submit/entry.latte
  app/FyziklaniModule/templates/Submit/qrEntry.latte
  app/FyziklaniModule/templates/Submit/table.latte
  app/FyziklaniModule/templates/Task/import.latte
  app/FyziklaniModule/templates/Task/table.latte
Labels: FOF

#296 add new backgraound
  app/templates/@layout.v4.latte
  www/css/login.css
  www/images/bg/3.jpg
Labels: UI & Front-end (CSS+JS+HTML)

#295 Fix zakladania orgov do ďalších(nových) ročníkov.
  app/Components/Forms/Factories/OrgFactory.php
Labels: bug
